# Generated by Django 6.0.6 on 2026-06-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(max_length=200)),
                ('drug_class', models.CharField(max_length=200)),
                ('moa', models.TextField()),
                ('dosage', models.CharField(max_length=200)),
                ('dosingSched', models.CharField(max_length=200)),
                ('bbLabel', models.TextField()),
                ('advEffects', models.CharField(max_length=200)),
            ],
        ),
    ]
