# Generated by Django 6.0.6 on 2026-07-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='bbLabel',
            new_name='avail_strengths',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='advEffects',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='dosage',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='dosingSched',
        ),
        migrations.AddField(
            model_name='drug',
            name='boxed_warnings',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drug',
            name='dosing_regimen',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drug',
            name='other_fda_ind',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drug',
            name='primary_fda_ind',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drug',
            name='side_effects',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
