# Generated by Django 6.0.6 on 2026-07-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_rename_bblabel_drug_avail_strengths_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drug',
            options={'ordering': ['ranking']},
        ),
        migrations.AddField(
            model_name='drug',
            name='ranking',
            field=models.PositiveSmallIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drug',
            name='boxed_warnings',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='drug',
            name='other_fda_ind',
            field=models.TextField(blank=True, default=''),
        ),
    ]
