# Generated by Django 5.2.6 on 2026-08-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0004_examattempt_examanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examattempt',
            name='mode',
        ),
        migrations.AddField(
            model_name='examattempt',
            name='allowed_formats',
            field=models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('free_text', 'Free text'), ('both', 'Both')], default='multiple_choice', max_length=20),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='question_mode',
            field=models.CharField(choices=[('recall', 'Recall'), ('identify', 'Identify'), ('mixed', 'Mixed')], default='recall', max_length=20),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='selection_mode',
            field=models.CharField(choices=[('ranged', 'Ranged'), ('random', 'Random'), ('missed', 'Missed')], default='ranged', max_length=20),
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='answer_format',
            field=models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('free_text', 'Free text')], max_length=20),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='ranking_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examattempt',
            name='ranking_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
